module.exports = {
  publicRuntimeConfig: {
    NEXT_PUBLIC_FETCH_URL: process.env.NEXT_PUBLIC_FETCH_URL,
    NEXT_PUBLIC_META_TITLE: process.env.NEXT_PUBLIC_META_TITLE,
    NEXT_PUBLIC_DOMAIN_URL: process.env.NEXT_PUBLIC_DOMAIN_URL,
    NEXT_PUBLIC_CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
    NEXT_PUBLIC_CLIENT_SECRET: process.env.NEXT_PUBLIC_CLIENT_SECRET,
    NEXT_PUBLIC_SSO_URL: process.env.NEXT_PUBLIC_SSO_URL,
    NEXT_PUBLIC_FRONT_URL: process.env.NEXT_PUBLIC_FRONT_URL,
    NEXT_PUBLIC_OTP_EXPIRE_TIME: process.env.NEXT_PUBLIC_OTP_EXPIRE_TIME,
  },
}
