const routes = {
  home: "/",
  courseDetail: "/course-detail",
  courseDetailSlug: "/course-detail/[slug]",
  cart: "/cart",
  notification: "/notification",
  purchaseHistory: "/purchase-history",
  editProfile: "/profile-setting",
  changePassword: "/change-password",
  login: "/login",
  register: "/register",
  aboutUs: "/about-us",
  privacy: "/privacy-policy",
  terms: "/terms",
  aboutUsMobile: "/mobile/about-us",
  privacyMobile: "/mobile/privacy-policy",
  termsMobile: "/mobile/terms",
  category: "/category",
  categorySlug: "/category/[slug]",
  checkout: "/checkout",
  myLearning: "/my-learning",
  myLearningSlug: "/my-learning/[slug]",
  sitemap: "/sitemap",
  certificate: "/certificate",
  yourAddresses: "/address",
  addAddress: "/address/add",
  rewardPointsHistory: "/reward-point-history",
  forgotPassword: "/forgot-password",
  resetPass: "/reset-password",
  otp: "/otp",
  privacyPolicy: "/privacy-policy",
  termsCondition: "/terms-condition",
  paymentFail: "/payment-fail",
}
export default routes
