/* eslint-disable prettier/prettier */
const routes = {
  dashboard: "/dashboard",
  login: "/login",
  forgorPassword: "/forgot-password",
  resetPassword: "/reset-password",
  roles: "/roles",
  otp: "/otp",
  permissions: "/permission",
  users: "/users",
  master: "/master",
  submaster: "/submaster",
  profile: "/profile",
  learner: "/learner",
  course: "/courses",
  widget: "/widgets",
  addWidget: "/add-widgets",
  page: "/page",
  orders: "/orders",
  transactions: "/transactions",
  coupon: "/coupon",
  notificationManage: "/notification-manage",
  analytics: "/analytics",
  privacyPolicy: "/privacy-policy",
  termsOfUse: "/terms-of-use",
  addCourse: "/add-course",
  editCourse: "/edit-course",
  category: "/programs",
  categoryAnalytics: "/program-analytics",
  instructor: "/instructor",
  reviews: "/reviews",
  country: "/country",
  province: "/state",
  city: "/city",
  zipCode: "/zip-code",
  error404Page: "/404",
  earning: "/earning",
  instructorAnalytics: "/instructor-analytics",
  certificate: "/certificate",
  addPayout: "/payouts",
  payout: "/payout",
}

export default routes
