const COUPON_TYPES = {
    BUY_X_GET_X: "BUY_X_GET_X",
    FLAT_DISCOUNT: "FLAT_DISCOUNT",
    PERCENTAGE_DISCOUNT: "PERCENTAGE_DISCOUNT"
};

const COUPON_CRITERIA = {
    COUPON_CRITERIA_ALL: "COUPON_CRITERIA_ALL",
    COUPON_CRITERIA_COURSES: "COUPON_CRITERIA_COURSES",
    COUPON_CRITERIA_CATEGORIES: "COUPON_CRITERIA_CATEGORIES"
};

module.exports = {
    COUPON_TYPES,
    COUPON_CRITERIA
}