const GENERAL_NOTIFICATION_CRITERIA_TYPE = {
    ALL: "GENERAL_NOTIFICATION_ALL",
    SELECTED_USER: "SELECTED_USER",
    WISHLIST: "WISHLIST",
    CART: "CART",
    PREVIOUS_ORDER: "PREVIOUS_ORDER"
}

const NOTIFICATION_TYPE = {
    GENERAL :"GENERAL",
    FLOATING: "FLOATING"
}

const USER_TYPE = {
    USER_TYPE_ALL: "USER_TYPE_ALL",
    LOGGEDIN_USER: "LOGGEDIN_USER",
    GUEST_USER: "GUEST_USER"

}

module.exports = {
    GENERAL_NOTIFICATION_CRITERIA_TYPE,
    NOTIFICATION_TYPE,
    USER_TYPE
}