const TOP_LIST_SETTINGS = {
    TOP_COURSE:'TOP_COURSE',
    TOP_CATEGORY: 'TOP_CATEGORY'
}
const BADGE_SETTINGS = {
    NEW_PUBLISHED: 'NEW_PUBLISHED',
    BEST_RATED: 'BEST_RATED',
    HOT_SELLING: 'HOT_SELLING'
}

const PAGES = {
    ABOUT_US: "ABOUT_US",
    PRIVACY_POLICY: "PRIVACY_POLICY",
    TERMS_AND_CONDITIONS: "TERMS_AND_CONDITIONS"
}

const REWARD = {
    REWARD_CALC : "REWARD_CALC"
}

const FIREBASE_PRIVATE_KEY = "FIREBASE_PRIVATE_KEY"

const SETTING_CODE = {
    IN_APPS_PURCHASE_DETAILS: "IN_APPS_PURCHASE_DETAILS"
}


module.exports = {
    TOP_LIST_SETTINGS: TOP_LIST_SETTINGS,
    BADGE_SETTINGS: BADGE_SETTINGS,
    SETTING_CODE:SETTING_CODE,
    PAGES,
    REWARD,
    FIREBASE_PRIVATE_KEY
}