const nextTranslate = require("next-translate")

module.exports = nextTranslate({
  publicRuntimeConfig: {
    NEXT_PUBLIC_FETCH_URL: process.env.NEXT_PUBLIC_FETCH_URL,
    NEXT_PUBLIC_META_TITLE: process.env.NEXT_PUBLIC_META_TITLE,
    NEXT_PUBLIC_CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
    NEXT_PUBLIC_CLIENT_SECRET: process.env.NEXT_PUBLIC_CLIENT_SECRET,
    NEXT_PUBLIC_SSO_URL: process.env.NEXT_PUBLIC_SSO_URL,
    NEXT_PUBLIC_DOMAIN_URL: process.env.NEXT_PUBLIC_DOMAIN_URL,
    NEXT_PUBLIC_ANDROID_APP_URL: process.env.NEXT_PUBLIC_ANDROID_APP_URL,
    NEXT_PUBLIC_ISO_APP_URL: process.env.NEXT_PUBLIC_ISO_APP_URL,
    NEXT_PUBLIC_OGM_URL: process.env.NEXT_PUBLIC_OGM_URL,
    NEXT_PUBLIC_PHONE_NUMBER: process.env.NEXT_PUBLIC_PHONE_NUMBER,
    NEXT_PUBLIC_OTP_EXPIRE_TIME: process.env.NEXT_PUBLIC_OTP_EXPIRE_TIME,
    NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING,
    NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
    NEXT_PUBLIC_AMPLITUDE_API_KEY: process.env.NEXT_PUBLIC_AMPLITUDE_API_KEY,
    NEXT_PUBLIC_GET_TOKEN_VAPIKEY: process.env.NEXT_PUBLIC_GET_TOKEN_VAPIKEY,
    NEXT_PUBLIC_PAYTM_MERCHANTS: process.env.NEXT_PUBLIC_PAYTM_MERCHANTS,
  },
  webpack: (config, { isServer, webpack }) => {
    return config
  },
})
